Working
kelibst/Weather-me pull request #1
Opened 2020-08-13 13:52 UTC by kelibst

- Loads weather Content directly to the page using Javascript.
- Loads the weather for Accra when the page loads.
- User can search for a location and the weather is diplayed for the location.
- Displays related search for city
- Responsive

2020-08-14 02:22 UTC, uryelah requested changes
Hi **Keli Dogbevi**, I'm Sarah your reviewer for this PR 👩‍🚀 

You've built a really nice weather app! Good job dealing with APIs, there are some other issues still but you've grasped the most important part so it will be a piece of cake to fix the remaining issues! 
You've got this 🦾 

# Required Changes 🏗️ 🐛 💡
 
- [ ] The appearance of the app should change, as [mentioned here](https://www.theodinproject.com/courses/javascript/lessons/weather-app), according to the data received from the API, you can try changing the background images according to the climate of each location for example. 

- [ ] You have a lot of DOM manipulation at the script.js file, while it works it's always best to keep your logic and your DOM manipulation separated. Try to refactor the places where you manipulate the DOM, document.querySelector, document.getElem..., innerHTMl, etc, as modular single purpose functions at the appropriated file.

- [ ] [OPTIONAL] The error message when no city is found is a nice addition, but notice that it only works the first time, if you dismiss it and try to search for another invalid city it will not show up again. Also after the first time it shows up if you dismiss it the whole info at the right tab will go up and lose that extra spacing at the top.

- [ ] [OPTIONAL] When your project is complete try to keep your keys as environmental variables file, it's a best practice to follow to keep your keys safe. [You can read more here on how to achieve it with webpack.](https://webpack.js.org/plugins/environment-plugin/)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-14 02:22 UTC, uryelah commented on dist/assets/styles/main.css
> +    background-image: linear-gradient(0deg, #171616, #00000038), url(https://images.unsplash.com/photo-1559707276-acebbece9d14?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=
- [ ] Think about how you can make this background image change.

2020-08-14 02:22 UTC, uryelah commented on src/script.js
> +      node.appendChild(container);
- [ ] Make sure that DOM manipulation such as this and the document queries below are in another file inside their own functions, then you can call the functions here.

2020-08-16 14:29 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-08-16 14:29 UTC, suretrust commented on src/dom.js
> +function renderContents() {
- You should use arrow functions instead of the function keyword throughout your app.`[Optional]`
```suggestion
const renderContents = () => {
```

2020-08-24 07:52 UTC, merged